### ISSUE TITLE
The default color doesn't do anything that I can tell

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/attack-powered-suit#15]
I would expect my bookmarked techniques to be colored black in this case but they aren't. Even if I select a different default color, nothing happens.

![image](https://user-images.githubusercontent.com/22311332/181865866-a8f7bf54-02e9-4d2e-95e8-a0063ba68f7e.png)

**Comment by mehaase** [comment]
This has been addressed in #23, where we observed that "color" and "score" interfere with each other, i.e. Navigator will ignore the requested color because the item has a score. The solution in that PR was to add a toggle to switch between score more and color mode. In both modes, the default color is meaningless, so we removed it. Thank you for catching this @clr2of8!

Score mode:

<img width="791" alt="Screen Shot 2022-12-22 at 1 45 56 PM" src="https://user-images.githubusercontent.com/320904/209205712-f1be0b75-6b6e-416f-9bcb-8f7a9062f377.png">

Color mode:

<img width="789" alt="Screen Shot 2022-12-22 at 1 46 04 PM" src="https://user-images.githubusercontent.com/320904/209205687-47bc4b7c-e43c-49e1-995e-0ad29573e391.png">
