### ISSUE TITLE
Expose technique when displaying subtechniques

### ISSUE THREAD

**Issue by jakewarren** [center-for-threat-informed-defense/attack-powered-suit#41]
**What capability are you seeking? What do you want to be able to do?**

When searching for specific subtechniques there are some that have "name collisions" in the search results. One example is `Spearphishing Attachment`, in the current output it is difficult to determine which technique the entry belongs to (could be `Phishing` [T1566] or `Phishing for Information` [T1598]) if you do not have the technique IDs memorized. 

It would be helpful if the parent technique could be displayed for subtechniques to make it easier to resolve these, perhaps controlled by a setting to allow users to control the output. A non-exhaustive list of other examples is Spearphishing Link, Web Services, Social Media Accounts, Server.

Screenshot:
<img width="588" alt="2023-06-01 10-39-25" src="https://github.com/center-for-threat-informed-defense/attack-powered-suit/assets/6472686/7060991d-36f2-4ac4-b288-c3f2b9cb7ed9">

**Are there any existing features that come close to doing what you need? Explain why those features aren't quite right.**
No existing features to my knowledge.

**Do you have any ideas about how the feature would work?**
For subtechniques, the technique could be displayed alongside subtechnique name. 

I am not sure the best way to approach the format specification but it would also be amazing to have the ability to include the parent technique when copying the output. Many people in the community will represent a subtechnique such as T1204.002  along the lines of `T1204.002 - User Execution: Malicious File`

Mockup Screenshot:
![2023-06-01 12-54-34](https://github.com/center-for-threat-informed-defense/attack-powered-suit/assets/6472686/37736070-028d-4f0a-bed3-af4473cc57f3)

> If you want to express positive or negative feedback on a bug report, please leave a Thumbs Up or Thumbs Down so that we can keep track of demand. Please do not reply just to say +1 or -1. Thanks!

**Comment by mehaase** [comment]
This is fixed in #47. Here's an example of what it looks like when searching for "spearphishing". Compare to Jake's original post above.

![Screenshot 2024-02-12 at 9 56 43 AM](https://github.com/center-for-threat-informed-defense/attack-powered-suit/assets/320904/c0f61fa2-f616-40ec-bb2c-07191f0be853)

And here's an example showing highlighting and result ranking are handled for parent/child techniques.

![Screenshot 2024-02-12 at 9 57 46 AM](https://github.com/center-for-threat-informed-defense/attack-powered-suit/assets/320904/990cafc2-9ea3-43b8-b03e-93a1fb1c9fc9)
